
#     _  __                 _    _                _     _____ _   _      _
#    | |/ /                | |  | |              | |   / ____| | (_)    | |
#    | ' / _ __   ___   ___| | _| |__   __ _  ___| | _| (___ | |_ _  ___| | __
#    |  < | '_ \ / _ \ / __| |/ / '_ \ / _` |/ __| |/ /\___ \| __| |/ __| |/ /
#    | . \| | | | (_) | (__|   <| |_) | (_| | (__|   < ____) | |_| | (__|   <
#    |_|\_\_| |_|\___/ \___|_|\_\_.__/ \__,_|\___|_|\_\_____/ \__|_|\___|_|\_\

# By Vieel
# Version 1.0

#  ● STICK ●
# Name of stick
name: "§bKnockback §3Stick"
# Message of stick
message: "§bStick works!"

#  ● PERMISSION ●
# Permission for use stick
permission: "knockbackstick.usage"
# No permission message
no-permission: "§cYou do not have permission to run this command"
